echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "I am learning"
echo "This is branch CHG0123456 code"
echo "Learning Webhook Date:19july2026"
